const API_BASE_URL =
  import.meta.env.VITE_API_BASE_URL || "http://localhost:5266/api/v1";//A verificar

  async function apiFetch(path, options = {}) {// Função Genérica para fazer requisições à API
  const url = `${API_BASE_URL}${path}`;

  const { method = "GET", body, headers } = options;

  const response = await fetch(url, {
    method,
    headers: {
      ...(body ? { "Content-Type": "application/json" } : {}),
      ...(headers || {}),
    },
    body: body ? JSON.stringify(body) : undefined,
  });

  if (!response.ok) {
    let errorText;
    try {
      errorText = await response.text();
    } catch {
      errorText = "Unknown error";
    }
    throw new Error(`API error (${response.status}): ${errorText}`);
  }

  const text = await response.text();
  return text ? JSON.parse(text) : null;
}

/**
 * OPENINGS (vagas)
 * Controller: OpeningController
 * Route base: api/v1/Opening
 */

// GET /api/v1/Opening
export function getOpenings() {
  return apiFetch("/Opening");
}

// GET /api/v1/Opening/{id}
export function getOpening(id) {
  return apiFetch(`/Opening/${id}`);
}

// POST /api/v1/Opening
export function createOpening(openingData) {
  return apiFetch("/Opening", {
    method: "POST",
    body: openingData,
  });
}

// PATCH /api/v1/Opening/{id}
export function updateOpening(id, partialData) {
  return apiFetch(`/Opening/${id}`, {
    method: "PATCH",
    body: partialData,
  });
}

// DELETE /api/v1/Opening/{id}
export function deleteOpening(id) {
  return apiFetch(`/Opening/${id}`, {
    method: "DELETE",
  });
}


/**
 * EMPLOYEES
 * Controller: EmployeeController
 * Route base: api/v1/Employee
 */

// GET /api/v1/Employee
export function getEmployees() {
  return apiFetch("/Employee");
}

// GET /api/v1/Employee/{id}
export function getEmployee(id) {
  return apiFetch(`/Employee/${id}`);
}

// POST /api/v1/Employee
// Expects an EmployeeWithPersonDTO-like object:
// {
//   personType: "...",
//   firstName: "...",
//   lastName: "...",
//   employeeDTO: { ... }
// }
export function createEmployee(employeeWithPersonData) {
  return apiFetch("/Employee", {
    method: "POST",
    body: employeeWithPersonData,
  });
}

// PATCH /api/v1/Employee/{id}
// Expects an EmployeeDTO-like object in the body,
// including BusinessEntityID to satisfy backend validation.
export function updateEmployee(id, employeePartialDto) {
  return apiFetch(`/Employee/${id}`, {
    method: "PATCH",
    body: employeePartialDto,
  });
}


/**
 * CandidateInfo
 * Controller: CandidateInfoController
 * Route base: api/v1/CandidateInfo
 */
// GET /api/v1/CandidateInfo
export function getCandidateInfos() {
  return apiFetch("/CandidateInfo");
}

// GET /api/v1/CandidateInfo/{id}
export function getCandidateInfo(id) {
  return apiFetch(`/CandidateInfo/${id}`);
}

// POST /api/v1/CandidateInfo
// Expects a CandidateInfoDTO-like object:
// {
//   // ID is generated by the backend; no need to send it
//   jobCandidateID: 0,       // optional: if you already have a JobCandidate
//   openingID: 123,          // opening this candidate is applying to
//   jobTitle: "...",
//   nationalID: "...",
//   birthDate: "2025-01-01T00:00:00" (or null),
//   maritalStatus: "...",
//   gender: "...",
//   firstName: "...",
//   middleName: "...",
//   lastName: "...",
//   email: "...",
//   phoneNumber: "...",
//   comment: "..."
// }
export function createCandidateInfo(candidateData) {
  return apiFetch("/CandidateInfo", {
    method: "POST",
    body: candidateData,
  });
}

// PATCH /api/v1/CandidateInfo/{id}
// Expects a CandidateInfoDTO-like object in the body,
// including JobCandidateID to satisfy backend validation.
export function updateCandidateInfo(id, candidatePartialDto) {
  return apiFetch(`/CandidateInfo/${id}`, {
    method: "PATCH",
    body: candidatePartialDto,
  });
}

// DELETE /api/v1/CandidateInfo/{id}
export function deleteCandidateInfo(id) {
  return apiFetch(`/CandidateInfo/${id}`, {
    method: "DELETE",
  });
}


/**
 * JobCandidate
 * Controller: JobCandidateController
 * Route base: api/v1/JobCandidate
 */

// GET /api/v1/JobCandidate
export function getJobCandidates() {
  return apiFetch("/JobCandidate");
}

// GET /api/v1/JobCandidate/{id}
export function getJobCandidate(id) {
  return apiFetch(`/JobCandidate/${id}`);
}

// POST /api/v1/JobCandidate
// Expects a JobCandidateDTO-like object:
// {
//   jobCandidateID: 0,          // optional, set by backend
//   businessEntityID: 0,        // if applicable
//   resume: "...",              // XML or text
//   resumeFile: "base64string"  // if using file storage
// }
export function createJobCandidate(candidateDto) {
  return apiFetch("/JobCandidate", {
    method: "POST",
    body: candidateDto,
  });
}

// PATCH /api/v1/JobCandidate/{id}
// Expects a JobCandidate-like object in the body,
// including JobCandidateID to satisfy backend validation.
export function updateJobCandidate(id, candidatePartial) {
  return apiFetch(`/JobCandidate/${id}`, {
    method: "PATCH",
    body: candidatePartial,
  });
}

// DELETE /api/v1/JobCandidate/{id}
export function deleteJobCandidate(id) {
  return apiFetch(`/JobCandidate/${id}`, {
    method: "DELETE",
  });
}